version: '3.8'

services:
  docs:
    build: .
    restart: always
    ports:
      - 50030:443
    volumes:
      - ./docs:/usr/local/apache2/htdocs/css
      - ./src:/usr/local/apache2/htdocs/scss
    networks:
      - development

networks:
  development:
    external: true
